### ISSUE TITLE
Read state isn't completely synchronized

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#124]
If articles are read on Inoreader website, they won't be deleted from offline database with next sync.

**Comment by Tunous** [comment]
I'm assuming that you are using Inoreader. Is that right?

## Notes to self

**Inoreader:**
Right now the app only checks the latest articles and doesn't load further once found existing articles. Need to perform additional requests in order to update the internal database with correct state of older articles.

- http://www.inoreader.com/developers/item-ids - for fetching ids
- http://www.inoreader.com/developers/article-ids - for converting ids

**Feedbin:**
Should already work correctly but needs additional testing.
- https://github.com/feedbin/feedbin-api/blob/master/content/unread-entries.md - for fetching unread ids

**Comment by kontrastylez** [comment]
Correct, I'm using Inoreader.

**Comment by kontrastylez** [comment]
Same behaviour for starred articles. If an article is unstarred on Inoreader website, it stays starred in SwipeNews.

**Comment by Tunous** [comment]
Fixed

**Comment by Tunous** [comment]
Note that in case of starred articles the API doesn't return correct state after the subscription has been removed. So if you have any starred articles for which the subscription no longer exists then their state won't be synchronized. I don't see any fixes for this situation.
