### ISSUE TITLE
Articles aren't marked as read, when tablet layout is enabled

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#92]
Version 0.20.2

**Comment by Tunous** [comment]
Pressing on mark as read button doesn't do anything?

**Comment by kontrastylez** [comment]
Manually marking as read works. But if you select an article in article list, so that it is opened in the right article content screen, the article isn't marked as read.

**Comment by Tunous** [comment]
That was actually done on purpose as I wasn't sure about the new behavior. 

With this new split layout every time you open the app it automatically selects first article and displays it to the right. With auto marking as read on article click that article would be marked as read. So basically whenever you opened the app it always marked first article as read. I considered it potentially dangerous because if you accidently opened the app and didn't unmark the article it could disappear unnoticed. 

Now I think that maybe instead of disabling this entirely I could only disable it for that single automatically opened article. Do you think that this would be a valid solution? Or maybe I'm just wrong and it's not necessary to disable this behavior at all...

**Comment by kontrastylez** [comment]
Disabling it only for the first article could be confusing for the user. I think the better solution would be, if the first article wouldn't be opened automatically.

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve article opening/marking as read with split layout](https://trello.com/c/zF3VxRRy/1034-improve-article-opening-marking-as-read-with-split-layout)

**Comment by Tunous** [comment]
- Article is no longer selected automatically
- Clicking on article marks it as read
- When no article is selected the main screen takes full width
- There is now a button which allows closing article split
