### ISSUE TITLE
Starring/Unstarring sometimes doesn't work

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#97]
Sometimes articles are not correctly marked as starred/unstarred. I have not yet fully understood, when this happens. But it seems, like this behavior does only appear, when an article has been opened directly in the browser (via swipe gesture or  article long press actions menu) before. There is no error message, the article simply isn't starred/unstarred after the next refresh.

**Comment by Tunous** [comment]
I have made many changes in how the app interacts with news providers in the coming update. (That's why it's taking so long to release - I need to do a lot of testing)

It's possible that this issue is fixed here so I'll mark it with that milestone and close. 

If you observe the problem again after you get the new version feel free to reopen.
